### ISSUE TITLE
Could you please make a new release with the trampoline patch?

### ISSUE THREAD

**Issue by jotoho** [ianpatt/skse64#1]
I am one of quite a few SkyrimSE players running the game on Linux instead of Windows using wine/proton and have been forced to use a version of SKSE64 not from skse.silverlock.org for quite a few months because of an issue with some "trampoline" code that causes SKSE64 to crash on launch. (Edit: On second thought, I think it instead continued executing the game but without SKSE64 so `getskseversion` and mods stopped working)

As far as I have been told, this bug has already been fixed by you many months ago (4a1e1219578890fb8cfb077daf08b386855ec62f) but ever since you committed that bugfix there has not been a new release so lots of players were either forced to stay with version `2.0.17` or use a custom build by the author of a popular Proton fork with said patch.

Sadly, not everyone got the news about that custom build and are still running into those issues because of it, so I want to ask if you could release a new official version in the not too distant future with that fix (and ideally the other improvements you have been working on since `2.0.19`). Are there any plans for new releases of SKSE64 for SkyrimSE in the next weeks/months?

What I know about this topic I got from these ProtonGE release notes (there's a section regarding SKSE64 compatibility including an explanation): https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.1-GE-1

**Comment by Ryan-rsm-McKenzie** [comment]
Can you do the same for fallout 4?

**Comment by ianpatt** [comment]
https://github.com/ianpatt/skse64/releases/tag/v2.0.20

**Comment by jotoho** [comment]
I have installed `2.0.20` and will try it out soon. Thanks!

Out of curiosity: Do you intend to use the GitHub releases for new versions in the future? Do you intend to upload the new version to [skse.silverlock.org](http://skse.silverlock.org)? I have always been taught that the only legit place for downloading SKSE is [skse.silverlock.org](http://skse.silverlock.org) so I would like to know where people should look for the latest SKSE version/download going forward.

**Comment by jotoho** [comment]
@ianpatt 

Just noticed that the new version is on [skse.silverlock.org](http://skse.silverlock.org) - it's just hidden in the archive section and not linked to on the webpage itself.

The line linking to the "current" version from the main page still refers to `2.0.19`:
```
Current SE build 2.0.19 (runtime 1.5.97): 7z archive
```

**Edit:** This has been resolved. Thanks!

**Comment by cirk2** [comment]
@ianpatt can that path also be applied to the sksevr build? I would build it for myself, but can not figure out how to build for skyrim vr.
