### ISSUE TITLE
The source code of Tag-2.1.5 compiles "skse64_1_6_323.dll"

### ISSUE THREAD

**Issue by CZhong-cn** [ianpatt/skse64#11]
4>skse64.vcxproj -> E:\Git\SKSE\skse64-2.1.5\x64\Debug\skse64_1_6_323.dll

**Comment by ianpatt** [comment]
The prebuilt projects are legacy and primarily maintained for people building plugins. If you are building the main executables, generate projects from cmake.

**Comment by CZhong-cn** [comment]
> The prebuilt projects are legacy and primarily maintained for people building plugins. If you are building the main executables, generate projects from cmake.

I want to develop a SKSE plugin, but I am using windows and vs2019. Do I need a  Debug  version of SKSE to attach and then add breakpoints? I'm referring to the getting started tutorial [here](https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/wiki/Getting-Started)

**Comment by ianpatt** [comment]
Ah, sorry - I meant that they are maintained for people who have existing plugin code bases that directly use the project files. You only need a debug version of SKSE if you want to make it easier to attach a debugger when starting up the game. You can build one with the instructions in the github (replacing Release with Debug).

**Comment by CZhong-cn** [comment]
I compiled a dll of version 1_6_323, which cannot be used in the latest SkyrimSE.

**Comment by CZhong-cn** [comment]
I see, I seem to need to rebuild a project with CMake
