### ISSUE TITLE
Plugin Developer Documentation

### ISSUE THREAD

**Issue by tbe** [ianpatt/skse64#17]
Hi there, 

is there any plugin developer documentation?

I tried to fix a broken plugin, but i don't even can it build. There are multiple issues either with the code i'm looking at or with
the skse64 project:

`PapyrusGame.cpp` contains multiple classes and definitions that are used by the plugin in question and the original author bundled a modified version of the skse64 source and includes the file directly. Is this common practice? Or should only the classes and types defined inside the header files considered usable?

How should a build process with headers from skse64 work? Are the system headers enough or must one realy include cpp files?

**Comment by lmstearn** [comment]
Hi @tbe,
Bit late, apologies, short answer, not really, best thing you can do is trawl through the SKSE code and replace his code with the updated. And seek and replace any old offsets. And it's easier to build all of SKSE than trying to section it.

There is a built, but untested version of it with the latest toolset and C++ version in this [WIP project](https://github.com/lmstearn/FuzzyQuasiSKSE), for example.
It's also worthwhile looking at [CommonLibSSE](https://github.com/Ryan-rsm-McKenzie/ExamplePlugin-CommonLibSSE), he's also got some Flash code for the UI which SKSE doesn't handle.
One of these days there'll be a speech-to-text version of [Sniffleman's video](https://www.youtube.com/watch?v=FLRhsrQ8mqw) on plugin dev which covers many bases.
One day I'll  get the translator out for [gottyduke's tutorial](https://github.com/gottyduke/PluginTutorialCN) as well. :smiley:
