### ISSUE TITLE
Command line option to ignore rest of options

### ISSUE THREAD

**Issue by zamadatix** [ianpatt/skse64#20]
To preface I'm aware of the other methods of launching SKSE straight from Steam (rename the .exe files, create a custom game entry, and so on) but these all have their own (minor) downsides such as when updates come around or resulting in duplicate entries for the game.

That said there is actually a way to get Steam to launch a specific executable instead of the one the game wants it to launch. If you go to the launch options for the game and specify `%command%` somewhere in the options string it will actually read the launch options as a full command not just arguments e.g. `"C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe" %command%` results in Steam launching skse64 with some garbage arguments. Unfortunately the garbage causes SKSE to error out and without it Steam will launch the default executable instead of SKSE.

What I'm asking here is would SKSE be interested in adding  (or at least accepting a PR for) an option like `-ignorerest` or similar so setting the Steam launch options to `"C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe" -ignorerest %command%` would work?

Thanks and sorry if there was a better place to send this!

**Comment by ianpatt** [comment]
This is generally for technical requests/issues, so this is close enough. Added in f49310bcd34f457fc4617d81b432022c5c7c9c35. Use `--` to terminate argument parsing.
