### ISSUE TITLE
Cant get SKSE.GetPluginVersion to report anything but -1

### ISSUE THREAD

**Issue by FriedTM** [ianpatt/skse64#23]
`Bool Function CheckNiOverride() 
    Return SKSE.GetPluginVersion("NiOverride") != -1 && NiOverride.GetScriptVersion() >= NIOVERRIDE_SCRIPT_VERSION
EndFunction`

this is the code I am using and I cant get it to respond with anything but -1. Is there something I am missing or is this function not working?

**Comment by ianpatt** [comment]
That isn't the name of the plugin.
