### ISSUE TITLE
Can't get SKSE to run no matter what.

### ISSUE THREAD

**Issue by Deejay85** [ianpatt/skse64#28]
I am trying to run SKSE. I have the address libraries and the engine fixes installed to the root directory of the Skyrim folder. So far, whenever I clicked on the skse64_loader.exe file, it runs just fine. However, when I try to run it from Mod Manager, I get an error message that reads the following:

```
You have updated to the Anniversary Edition (AE) of Skyrim. Please download the AE version of SKSE 64 from <site>

Runtime: 1.6.640

```
The headache I am having here is that I am *already* running the AE version of SKSE, which makes it even more odd when, even though the run option is pointing directly at the skse64_loader.exe file in Skyrim's root folder, it still refuses to run in Mod Manager no matter what I do. So far I have attempted to uninstall the game, copy a backup of a fresh install into the directory, let it verify the files as needed, run the game launcher from Steam, adjust the settings, save, and then exit. Again…everything works fine as long as I click on the folder... It's only when using Mod Manager that things tend to fall apart.

Even more odd, even when I delete said files, run the skse64_loader.exe (that now no longer exists due to me having deleted it), I still get the exact same message…somehow. I'm sure there is a cached image somewhere that it is pulling from, because under normal circumstances, this should not happen…and no…cleaning the temporary files, and then restarting the computer, didn't fix the problem either.

I understand this isn't normal, and frankly, I am at a lost here. I'm willing to try anything to get it to work, so if you have any ideas, I am willing to give it a try.

**Comment by ianpatt** [comment]
This is not a technical support forum, and your issue is not with SKSE. Most likely you and your mod manager disagree on the folder to which you have installed Skyrim.
