### ISSUE TITLE
common_vc14 ?

### ISSUE THREAD

**Issue by calebtt** [ianpatt/skse64#29]
Where can I obtain common_vc14, is it necessary, and have you considered updating from Windows SDK 8.1 to something newer?
Windows 8.1 SDK isn't even in the list of options for the VS installer anymore, so it would need to be downloaded from Microsoft's website.

And while I'm at it, any plans to upgrade to VS2022 project files?

**Comment by ianpatt** [comment]
The project files are legacy for developers with pre-existing projects. Use cmake.
