### ISSUE TITLE
Add launch option to make skse-loader silent (for Steam Deck users)

### ISSUE THREAD

**Issue by Star-X555** [ianpatt/skse64#31]
Right now SKSE loader outputs its logs in a terminal.  On a normal desktop PC this is fine, but on Steam Deck it could be an issue.  While Valve fixed the bug that made Skyrim unplayable from this, I believe it causes sound issues when activating sleep mode, which isn't fixed by the pause plugin from Decky due to there being two windows instead of one.

Easiest solution I feel is to add a command line argument that toggles the console output so that the game just launches without a window filled with debug info.  That way it's there by default, but users playing on Steam Deck can toggle the debug output if they wish.

**Comment by ianpatt** [comment]
Many processes write to stdout. This needs to be fixed on the Proton side.
