### ISSUE TITLE
Saving the game crashes

### ISSUE THREAD

**Issue by juliocoliveira** [ianpatt/skse64#33]
If I launch with SKSE it crashes when trying to save, Even with no plugins enabled (skse64 plugins, DLLs).
If I launch without SKSE it saves normally.

Using the latest version of Skyrim Anniversary Edition (1.6.1130) and the latest SKSE64 version (2.2.4).

**Comment by ianpatt** [comment]
Works on my machine, haven't seen any reports of this.

**Comment by juliocoliveira** [comment]
Yeah, the problem was not SKSE64 but because I uninstalled SKYUI because was crashing.
I installed this mod: https://www.nexusmods.com/skyrimspecialedition/mods/14024?tab=posts and with it I was able to save.
