### ISSUE TITLE
SKSE not working with the gog version

### ISSUE THREAD

**Issue by ghost** [ianpatt/skse64#37]
SKSE does not work on the gog version. 2.2.3 gives the new version error while 2.2.6 boots the game. However anything needing SKSE does not load with 2.2.6. For example, skyui gives an error about SKSE not being loaded despite being launched with the loader

**Comment by ianpatt** [comment]
Steam 2.2.6 should not attempt to launch the GOG executable; that's a bug. An informative error message should be displayed. The proper GOG version is delayed while they prepare a patch to fix some compatibility problems.

**Comment by ianpatt** [comment]
Fixed in 9466baa561a0837de377c25dd87d5c1d55df76bb, thanks.

**Comment by ghost** [comment]
Could you update silverlock.org to clarify that the 1170 gog version will
come later? I don’t think too many people will see your nexus comments or
this issue

**Comment by ianpatt** [comment]
Yes.

**Comment by ghost** [comment]
Did they give an ETA on when the update is supposed to come out?

**Comment by ianpatt** [comment]
They did not.
