### ISSUE TITLE
In GameAPI.cpp g_mainHeap and g_consoleHandle share the same offset

### ISSUE THREAD

**Issue by Hugues92** [ianpatt/skse64#4]
0x01F57A80 looks correct for g_mainHeap, but it should not also be g_consoleHandle.

**Comment by ianpatt** [comment]
Thanks, fixed in 03f236fdf12101ad586a5a2bc36d488c4914f306.

**Comment by Hugues92** [comment]
You updated the search comment but not the actual offset :)

**Comment by ianpatt** [comment]
Oops, I didn't save before pushing. 213d3b91e366077d2107c57c219bbd9f2ae25179.
