### ISSUE TITLE
Couldn't Inject DLL in Winlator gaming emulation.

### ISSUE THREAD

**Issue by benknam** [ianpatt/skse64#43]
Tested game started & play in charming with clean installation,
game version : 1.6.1179.0.8 from GOG,
while started the game with SKSE64,
the command window hold and processing for a long time,
then showing " Couldn't Inject DLL ".

Here's the log:

skse64 loader 02020060 01DAE7207EE152BD 6.1 (7601)
config path = D:\Winlator\SkyrimAE\Data\SKSE\skse.ini
procPath = D:\Winlator\SkyrimAE\\SkyrimSE.exe
launching: SkyrimSE.exe (D:\Winlator\SkyrimAE\\SkyrimSE.exe)
dwSignature = FEEF04BD
dwStrucVersion = 00010000
dwFileVersionMS = 00010006
dwFileVersionLS = 049B0000
dwProductVersionMS = 00010006
dwProductVersionLS = 049B0000
dwFileFlagsMask = 00000017
dwFileFlags = 00000000
dwFileOS = 00000004
dwFileType = 00000001
dwFileSubtype = 00000000
dwFileDateMS = 00000000
dwFileDateLS = 00000000
productVersionStr = 1.6.1179.0
version = 00010006049B0000
product name = TESV: Skyrim
gog exe
dll = D:\Winlator\SkyrimAE\\skse64_1_6_1179.dll
main thread id = 304
hookBase = 0000000080110000
loadLibraryAAddr = 000000027FF2EA14
getProcAddressAddr = 000000027FF38D50
Process::InstallHook: waiting for thread = WAIT_TIMEOUT
Couldn't inject DLL.

Tested gaming with SKSE64 in Mobox (same game folder and files),
it works.
but while in Winlator,
it's just stuck at installing hook.

**Comment by ianpatt** [comment]
This is an issue with your emulator. I cannot provide technical support for it. If injection doesn't work, the emulator is broken.

**Comment by benknam** [comment]
> This is an issue with your emulator. I cannot provide technical support for it. If injection doesn't work, the emulator is broken.

Thanks for reply, bro.
I'm taking action to check with Winlator's sources code,
it might be the flag that box86/64 didn't give right response for hooking processing.
